# Generated by Django 3.0.4 on 2020-03-13 14:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appone', '0002_auto_20200313_1349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='protfol',
            new_name='protfoluser',
        ),
    ]
